// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
'use strict';
// Optional isolated UI check. HTML is injected; IDB and digest are simulated.
// It neither opens a user file URL nor touches a real browser profile.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {createHash}=require('node:crypto');
const {validateWorkspace}=require('../tools/contract.cjs');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const localApp=path.join(root,'LC_CHECKLIST.html');
const html=fs.readFileSync(fs.existsSync(localApp)?localApp:path.join(root,'index.html'),'utf8');
const mock=fs.readFileSync(path.join(root,'tests/browser_storage_mock.js'),'utf8');
const browserPath=process.env.CHROMIUM_EXECUTABLE;

(async()=>{
 const browser=await chromium.launch({headless:true,...(browserPath?{executablePath:browserPath}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('__digest',bytes=>[...createHash('sha256').update(Buffer.from(bytes)).digest()]);
 await page.evaluate(mock);
 await page.evaluate(()=>Object.defineProperty(crypto,'subtle',{configurable:true,value:{digest:async(_algorithm,bytes)=>Uint8Array.from(await __digest([...new Uint8Array(bytes)])).buffer}}));
 await page.setContent(html);
 await page.waitForFunction(()=>window.Clearings?.storage().ready);
 const username=page.locator('#welcomeName');
 assert.equal(await username.inputValue(),'');
 assert.equal(await username.getAttribute('placeholder'),'Your Username');
 assert.equal(await username.evaluate(e=>e.matches(':placeholder-shown')),true);
 assert.ok(Number(await username.evaluate(e=>getComputedStyle(e,'::placeholder').opacity))<1);
 await page.locator('#tryExample').click();
 assert.equal(await page.locator('#welcomeDialog').evaluate(e=>e.open),true,'A username is required before starting');
 await username.fill('First editor');
 assert.equal(await username.evaluate(e=>e.matches(':placeholder-shown')),false);
 await page.locator('#tryExample').click();
 assert.equal((await page.evaluate(()=>Clearings.snapshot())).index.preferences.displayName,'First editor');
 await page.waitForFunction(()=>Clearings.storage().savedAt&&!Clearings.storage().dirty);
 if(process.env.CLEARINGS_PREVIEW){await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:process.env.CLEARINGS_PREVIEW,animations:'disabled'});}
 assert.equal(await page.locator('#libraryList .library-row').count(),2);
 assert.equal(await page.locator('#libraryList .grip[data-drag="library"]').count(),2);
 assert.equal(await page.locator('#libraryList .progress-track').first().evaluate(e=>e.getBoundingClientRect().width),58);
 assert.equal(await page.locator('#trackedList .progress-track').first().evaluate(e=>e.getBoundingClientRect().width),58);
 assert.equal(await page.locator('#addItemButton').innerText(),'New item');
 assert.equal(await page.locator('.new-list .add-plus').count(),2);
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.locator('.new-list[data-action="new-checklist"]').click();
 await page.locator('#dialogFields .new-checklist-details > summary').click();
 assert.ok(await page.locator('#dialogFields .new-checklist-details > .field').evaluate(e=>e.getAnimations().some(a=>a.effect.getTiming().duration>=600)));
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 assert.equal(await page.locator('.library-card .grip').count(),0);
 assert.equal(await page.locator('#centerFooter').isHidden(),true);
 assert.equal(await page.locator('#addItemButton').isEnabled(),true);
 assert.equal(await page.locator('#center [data-action="new-step"]').count(),0);
 assert.equal(await page.locator('[data-root-group="make"]').evaluate(e=>getComputedStyle(e).borderTopWidth),'0px');
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="preferences"]').click();
 assert.equal(await page.locator('[data-pref="showFooterProgress"]').isChecked(),false);
 assert.equal(await page.locator('[data-pref="showFooterTrack"]').isChecked(),false);
 await page.locator('[data-pref="showFooterProgress"]').check();
 assert.match(await page.locator('#centerFooter').innerText(),/counted complete/);
 await page.locator('[data-pref="showFooterTrack"]').check();
 assert.equal(await page.locator('#centerFooter [data-action="track-current"]').isVisible(),true);
 await page.locator('[data-pref="showFooterProgress"]').uncheck();
 await page.locator('[data-pref="showFooterTrack"]').uncheck();
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 assert.equal(await page.locator('#centerFooter').isHidden(),true);
 assert.equal(await page.locator('#clearIndicators').isHidden(),true);
 const refreshSize=await page.locator('#refreshButton').boundingBox();
 assert.ok(refreshSize.height>=50&&refreshSize.width>=200);
 const details=page.locator('#pageHeader details.about').first();
 assert.equal(await details.locator('.disclosure-glyph').count(),0);
 assert.equal(await details.evaluate(e=>e.open),false);
 await details.locator('summary').click();
 assert.equal(await details.evaluate(e=>e.open),true);
 await details.locator('summary').click();
 assert.equal(await details.evaluate(e=>e.open),false);
 await page.emulateMedia({reducedMotion:'no-preference'});
 const firstGroup=page.locator('#pageContent [data-root-group]').first(),fold=firstGroup.locator('.group-name'),realRows=firstGroup.locator(':scope > ol.rows:not([data-fold-visual])');
 assert.equal(await realRows.count(),1);
 assert.equal(await page.locator('#pageContent [data-root-group]').nth(1).locator(':scope > ol.rows').count(),0);
 assert.equal(await firstGroup.locator('[data-step-row="first-look"] > ol.rows').count(),0);
 const rootTrack=await firstGroup.locator(':scope > .group-header .progress-track').boundingBox(),childTrack=await firstGroup.locator('[data-step-row="first-look"] > .task-row .progress-track').boundingBox();
 assert.ok(childTrack.width<rootTrack.width);
 const nestedFold=firstGroup.locator('[data-step-row="first-look"] > .task-row .row-title');
 await nestedFold.press('Enter');
 const firstLevel=firstGroup.locator('[data-step-row="first-look"] > .task-row .row-title'),secondLevel=firstGroup.locator('[data-step-row="build-demo"] > .task-row .row-title');
 assert.ok(parseFloat(await secondLevel.evaluate(e=>getComputedStyle(e).fontSize))<parseFloat(await firstLevel.evaluate(e=>getComputedStyle(e).fontSize)));
 assert.ok((await secondLevel.boundingBox()).x>(await firstLevel.boundingBox()).x);
 await nestedFold.press('Enter');
 await firstGroup.locator('[data-fold-visual]').waitFor({state:'detached'});
 await fold.click();
 await page.waitForFunction(()=>document.querySelector('#pageContent [data-root-group] .group-name')?.getAttribute('aria-expanded')==='false');
 assert.equal(await fold.getAttribute('aria-expanded'),'false');
 assert.equal(await realRows.count(),0);
 assert.equal(await firstGroup.locator('[data-fold-visual]').count(),1);
 await page.waitForTimeout(200);
 assert.equal(await firstGroup.locator('[data-fold-visual]').count(),1);
 await firstGroup.locator('[data-fold-visual]').waitFor({state:'detached'});
 await fold.click();
 await page.waitForFunction(()=>document.querySelector('#pageContent [data-root-group] .group-name')?.getAttribute('aria-expanded')==='true');
 assert.equal(await fold.getAttribute('aria-expanded'),'true');
 assert.equal(await realRows.count(),1);
 assert.equal(await realRows.evaluate(e=>e.getAnimations().some(a=>a.playState==='running')),true);
 await fold.press('Enter');await fold.press('Enter');
 assert.equal(await realRows.count(),1);
 await page.waitForTimeout(600);
 assert.equal(await firstGroup.locator('[data-fold-visual]').count(),0);
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="preferences"]').click();
 await page.locator('[data-pref="motion"]').selectOption('reduce');
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 await fold.click();
 await page.waitForFunction(()=>document.querySelector('#pageContent [data-root-group] .group-name')?.getAttribute('aria-expanded')==='false');
 assert.equal(await realRows.count(),0);
 assert.equal(await firstGroup.locator('[data-fold-visual]').count(),0);
 await fold.click();
 await page.waitForFunction(()=>document.querySelector('#pageContent [data-root-group] .group-name')?.getAttribute('aria-expanded')==='true');
 assert.equal(await realRows.count(),1);
 assert.equal(await realRows.evaluate(e=>e.getAnimations().length),0);
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="preferences"]').click();
 await page.locator('[data-pref="motion"]').selectOption('system');
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 await fold.dblclick();
 assert.equal(await page.locator('#pageHeader h1').innerText(),'Shape the idea');
 assert.equal(await page.locator('#addItemButton').getAttribute('data-parent'),'shape');
 const alignment=await page.evaluate(()=>{const box=document.querySelector('#pageHeader .header-title-checkbox').getBoundingClientRect(),title=document.querySelector('#pageHeader h1').getBoundingClientRect();return Math.abs((box.top+box.bottom-title.top-title.bottom)/2)});
 assert.ok(alignment<4,`Focused title checkbox is ${alignment}px from the title center`);
 await page.waitForTimeout(340);
 assert.equal(await page.locator('#pageHeader h1').innerText(),'Shape the idea');
 await page.locator('#breadcrumbs [data-action="open-checklist"]').click();
 await firstGroup.locator('[data-step-row="purpose"] .row-title').dblclick();
 assert.equal(await page.locator('#pageHeader h1').innerText(),'Describe who it helps');
 await page.locator('#breadcrumbs [data-action="open-checklist"]').click();
 const from=await page.locator('#libraryList .grip[data-id="example-workshop"]').boundingBox();
 const to=await page.locator('#libraryList [data-library-id="example-overview"]').boundingBox();
 const centerDot=page.locator('#libraryList .grip[data-id="example-workshop"] i:nth-child(3)');
 const baseDotX=await centerDot.evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41);
 if(process.env.CLEARINGS_MORPH_REPORT)await page.evaluate(()=>{window.__hoverMorph=[];const dot=document.querySelector('#libraryList .grip[data-id="example-workshop"] i:nth-child(3)'),start=performance.now();const sample=t=>{window.__hoverMorph.push([t,new DOMMatrix(getComputedStyle(dot).transform).m41]);if(t-start<1250)requestAnimationFrame(sample)};requestAnimationFrame(sample)});
 await page.mouse.move(from.x+from.width/2,from.y+from.height/2);
 await page.waitForTimeout(140);
 const openingDotX=await centerDot.evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41);
 await page.waitForTimeout(1100);
 const circleDotX=await centerDot.evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41);
 assert.ok(openingDotX<baseDotX&&openingDotX>circleDotX,`Hover should ease dots outward: ${JSON.stringify({baseDotX,openingDotX,circleDotX})}`);
 await page.mouse.move(from.x+from.width+30,from.y-20);
 await page.waitForTimeout(1250);
 const returnedDotX=await centerDot.evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41);
 assert.ok(Math.abs(returnedDotX-baseDotX)<.05,`Leaving the grip should restore the bar: ${JSON.stringify({baseDotX,returnedDotX})}`);
 await page.mouse.move(from.x+from.width/2,from.y+from.height/2);
 await page.waitForTimeout(1250);
 await page.mouse.down();
 const dropX=to.x+to.width/2,dropY=to.y+4;
 await page.mouse.move(dropX,dropY,{steps:8});
 await page.waitForFunction(()=>{const g=document.querySelector('#dragGhost .ghost-grip');return !!g&&!document.getElementById('dragGhost').hidden});
 if(process.env.CLEARINGS_FRAME_REPORT)await page.evaluate(()=>{window.__holdFrameTimes=[];const record=t=>{if(document.getElementById('dragGhost').hidden)return;window.__holdFrameTimes.push(t);requestAnimationFrame(record)};requestAnimationFrame(record)});
 assert.equal(await page.locator('#dragGhost .ghost-grip i').count(),6);
 assert.equal(await page.locator('#dragGhost .ghost-grip i').first().evaluate(e=>getComputedStyle(e).width),'4px');
 await page.locator('#dragGhost .ghost-grip.grabbed').waitFor();
 await page.waitForTimeout(340);
 const spin=await page.locator('#dragGhost .ghost-grip').evaluate(e=>e.style.transform);
 assert.match(spin,/rotate\([1-9]/);
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const held=await page.locator('#dragGhost .ghost-grip').boundingBox();
 assert.ok(Math.abs(held.x+held.width/2-dropX)<4&&Math.abs(held.y+held.height/2-dropY)<4,JSON.stringify({held,dropX,dropY}));
 const releaseSpeed=await page.locator('#dragGhost .ghost-grip').evaluate(e=>new Promise(resolve=>{const angle=()=>Number(e.style.transform.match(/rotate\(([-.\d]+)/)?.[1]||0),first=angle(),start=performance.now();setTimeout(()=>resolve(((angle()-first+360)%360)*1000/(performance.now()-start)),90)}));
 await page.mouse.up();
 await page.locator('.drag-flight').waitFor({state:'visible'});
 const displaced=page.locator('#libraryList .library-row[data-library-id="example-overview"]');
 assert.ok(await displaced.evaluate(e=>e.getAnimations().some(a=>a.effect.getTiming().duration===800)),'The neighboring checklist should slide into its new slot');
 const displacedStart=await displaced.boundingBox();
 await page.waitForTimeout(250);
 const displacedMiddle=await displaced.boundingBox();
 assert.ok(displacedMiddle.y>displacedStart.y+2,`Neighbor should travel rather than jump: ${JSON.stringify({displacedStart,displacedMiddle})}`);
 if(process.env.CLEARINGS_SLIDE_PREVIEW)await page.screenshot({path:process.env.CLEARINGS_SLIDE_PREVIEW});
 if(process.env.CLEARINGS_MORPH_REPORT)await page.evaluate(()=>{window.__landingMorph=[];const dot=document.querySelector('.drag-flight .ghost-grip i:nth-child(3)');const sample=t=>{if(!dot.isConnected)return;window.__landingMorph.push([t,new DOMMatrix(getComputedStyle(dot).transform).m41]);requestAnimationFrame(sample)};requestAnimationFrame(sample)});
 if(process.env.CLEARINGS_FRAME_REPORT)await page.evaluate(()=>{window.__dragFrameTimes=[];const record=t=>{if(!document.querySelector('.drag-flight'))return;window.__dragFrameTimes.push(t);requestAnimationFrame(record)};requestAnimationFrame(record)});
 const landing=await page.locator('.drag-flight .ghost-grip').evaluate(e=>{const a=e.getAnimations()[0],frames=a.effect.getKeyframes();return {start:parseFloat(frames[0].transform.match(/rotate\(([-.\d]+)/)[1]),end:parseFloat(frames[1].transform.match(/rotate\(([-.\d]+)/)[1]),easing:a.effect.getTiming().easing,duration:a.effect.getTiming().duration}});
 const easing=landing.easing.match(/cubic-bezier\(([.\d]+),\s*([.\d]+)/);
 assert.ok(easing&&landing.end>landing.start&&landing.end-landing.start<360,`Grip should slow clockwise without waiting for a full turn: ${JSON.stringify(landing)}`);
 const initialLandingSpeed=(landing.end-landing.start)/(landing.duration/1000)*Number(easing[2])/Number(easing[1]);
 assert.ok(Math.abs(initialLandingSpeed-releaseSpeed)<55,`Landing should inherit pickup speed: ${JSON.stringify({releaseSpeed,landing,initialLandingSpeed})}`);
 await page.waitForTimeout(450);
 assert.equal(await page.locator('.drag-flight').isVisible(),true);
 assert.equal(await page.locator('.drag-flight .ghost-grip i').first().evaluate(e=>getComputedStyle(e).width),'4px');
 if(process.env.CLEARINGS_DRAG_PREVIEW)await page.screenshot({path:process.env.CLEARINGS_DRAG_PREVIEW});
 if(process.env.CLEARINGS_MORPH_PREVIEW){await page.waitForTimeout(650);await page.screenshot({path:process.env.CLEARINGS_MORPH_PREVIEW})}
 await page.locator('.drag-flight').waitFor({state:'detached'});
 if(process.env.CLEARINGS_MORPH_REPORT){for(const [name,points] of Object.entries(await page.evaluate(()=>({hover:window.__hoverMorph,landing:window.__landingMorph})))){const moves=points.slice(1).map(([t,x],i)=>({dt:t-points[i][0],dx:x-points[i][1]})),largest=Math.max(...moves.map(x=>Math.abs(x.dx))),changed=moves.filter(x=>Math.abs(x.dx)>.001).length;console.log(`Clearings ${name} morph: ${points.length} samples, ${changed} changing frames, largest step ${largest.toFixed(3)} px`)}}
 if(process.env.CLEARINGS_FRAME_REPORT){for(const [name,frames] of Object.entries(await page.evaluate(()=>({pickup:window.__holdFrameTimes,landing:window.__dragFrameTimes})))){const intervals=frames.slice(1).map((t,i)=>t-frames[i]).sort((a,b)=>a-b),elapsed=(frames.at(-1)-frames[0])/1000;console.log(`Clearings ${name} frames: ${frames.length} over ${elapsed.toFixed(2)} s; ${(frames.length/elapsed).toFixed(1)} fps; median ${intervals[Math.floor(intervals.length/2)]?.toFixed(1)} ms; p95 ${intervals[Math.floor(intervals.length*.95)]?.toFixed(1)} ms`)}}
 assert.equal((await page.evaluate(()=>Clearings.snapshot())).index.entries[0].id,'example-workshop');
 await page.locator('#libraryList .grip[data-id="example-workshop"]').focus();
 await page.keyboard.press('Shift+ArrowDown');
 assert.equal((await page.evaluate(()=>Clearings.snapshot())).index.entries[0].id,'example-overview');
 await page.keyboard.press('Shift+ArrowUp');
 assert.equal((await page.evaluate(()=>Clearings.snapshot())).index.entries[0].id,'example-workshop');
 const returnFrom=await page.locator('#libraryList .grip[data-id="example-workshop"]').boundingBox();
 await page.mouse.move(returnFrom.x+returnFrom.width/2,returnFrom.y+returnFrom.height/2);
 await page.mouse.down();
 await page.mouse.move(850,700,{steps:8});
 await page.waitForFunction(()=>!document.getElementById('dragGhost').hidden);
 await page.mouse.up();
 await page.locator('.drag-flight').waitFor({state:'visible'});
 const returningStart=await page.locator('.drag-flight').boundingBox();
 await page.waitForTimeout(250);
 const returningMiddle=await page.locator('.drag-flight').boundingBox();
 assert.ok(returningMiddle.x<returningStart.x-20,'An invalid drop should glide back toward its original row');
 if(process.env.CLEARINGS_RETURN_PREVIEW)await page.screenshot({path:process.env.CLEARINGS_RETURN_PREVIEW});
 await page.locator('.drag-flight').waitFor({state:'detached'});
 assert.equal((await page.evaluate(()=>Clearings.snapshot())).index.entries[0].id,'example-workshop');
 const focusFrom=await page.locator('#pageContent .grip[data-drag="step"]').first().boundingBox(),header=await page.locator('#pageHeader').boundingBox();
 await page.mouse.move(focusFrom.x+focusFrom.width/2,focusFrom.y+focusFrom.height/2);
 await page.mouse.down();
 await page.mouse.move(header.x+50,header.y+header.height/2,{steps:8});
 await page.waitForFunction(()=>!document.getElementById('dragGhost').hidden);
 await page.mouse.up();
 await page.locator('.drag-flight').waitFor({state:'visible'});
 assert.notEqual(await page.locator('#pageHeader h1').innerText(),'Program Overview');
 if(process.env.CLEARINGS_FOCUS_PREVIEW){await page.waitForTimeout(350);await page.screenshot({path:process.env.CLEARINGS_FOCUS_PREVIEW})}
 await page.locator('.drag-flight').waitFor({state:'detached'});
 await page.locator('#breadcrumbs [data-action="open-checklist"]').click();
 assert.equal(await page.locator('#pageHeader h1').innerText(),'Program Overview');
 await page.waitForFunction(()=>Clearings.storage().savedAt&&!Clearings.storage().dirty);
 const savedRecord=await page.evaluate(()=>window.__records.get('workspace:local'));
 const reopened=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await reopened.evaluate(mock);await reopened.evaluate(record=>window.__records.set('workspace:local',record),savedRecord);await reopened.setContent(html);
 await reopened.waitForFunction(()=>window.Clearings?.storage().ready);
 assert.equal(await reopened.locator('#pageHeader h1').innerText(),'Weekend Workshop');
 await reopened.close();
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="local-settings"]').click();
 await page.locator('[data-pref="openTopChecklist"]').uncheck();
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 await page.waitForFunction(()=>Clearings.storage().savedAt&&!Clearings.storage().dirty);
 const savedFallback=await page.evaluate(()=>window.__records.get('workspace:local'));
 const fallbackPage=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await fallbackPage.evaluate(mock);await fallbackPage.evaluate(record=>window.__records.set('workspace:local',record),savedFallback);await fallbackPage.setContent(html);
 await fallbackPage.waitForFunction(()=>window.Clearings?.storage().ready);
 assert.equal(await fallbackPage.locator('#pageHeader h1').innerText(),'Program Overview');
 await fallbackPage.close();
 // The new editor shows a single field; deliberate discard keeps no ghost item.
 await page.locator('#addItemButton').click();
 assert.equal(await page.locator('#dialogFields .optional-details').evaluate(e=>e.open),false);
 await page.locator('#dialogFields [name="title"]').fill('Discard this draft');
 page.once('dialog',d=>d.accept());
 await page.locator('[data-action="discard-editor"]').click();
 assert.equal(await page.evaluate(()=>Clearings.snapshot().documents[0].model.items.some(i=>i.text==='Discard this draft')),false);
 // Optional practice list installs once, without checking any step for the user.
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="local-settings"]').click();
 await page.locator('[data-action="add-smoke-checklist"]').click();
 let snapshot=await page.evaluate(()=>Clearings.snapshot());
 const smoke=snapshot.documents.find(d=>d.documentId==='clearings-smoke-test-v1');
 assert.ok(smoke);assert.equal(smoke.model.items.length,7);assert.deepEqual(smoke.state,{});
 assert.equal(snapshot.index.schemaVersion,4);
 // A refresh consumes a data-only proposal and still requires explicit approval.
 await page.locator('#libraryList [data-library-id="example-overview"] .library-open').click();
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="ai-context"]').click();
 const context=JSON.parse(await page.locator('#dialogFields .ai-source').inputValue());
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 const packet={format:'checklist-studio-changes',schemaVersion:1,documentId:'example-overview',baseSha256:context.baseSha256,operations:[{op:'update-item',id:'purpose',changes:{text:'Describe who this helps today'}}]};
 await page.locator('#refreshButton').click();
 await page.locator('#refreshInput').setInputFiles({name:'changes.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packet))});
 await page.waitForFunction(()=>document.getElementById('dialogTitle').textContent==='Review before applying');
 assert.equal((await page.evaluate(()=>Clearings.snapshot())).documents.find(d=>d.documentId==='example-overview').model.items.find(i=>i.id==='purpose').text,'Describe who it helps');
 await page.locator('[name="proposedBy"]').fill('Assistant tester');
 await page.locator('#dialogApply').click();
 snapshot=await page.evaluate(()=>Clearings.snapshot());
 assert.equal(snapshot.documents.find(d=>d.documentId==='example-overview').model.items.find(i=>i.id==='purpose').text,'Describe who this helps today');
 assert.ok(snapshot.index.activity.some(a=>a.itemId==='purpose'&&a.actor==='Assistant tester'&&a.approvedBy==='First editor'&&a.highlight&&a.unread));
 assert.equal(await page.locator('#checklistUnread').isVisible(),true);
 assert.equal(await page.locator('#center [data-step-row="purpose"] .change-tag').innerText(),'UPDATED');
 await page.locator('[data-action="library-view"]').first().click();
 assert.equal(await page.locator('#checklistUnread').isVisible(),false);
 assert.ok((await page.evaluate(()=>Clearings.snapshot())).index.activity.some(a=>a.itemId==='purpose'&&a.highlight&&!a.unread));
 await page.locator('#libraryList [data-library-id="example-overview"] .library-open').click();
 await page.locator('#center [data-step-row="purpose"] [data-menu="step"]').click();
 await page.locator('#menu [data-command="track-item"]').click();
 await page.locator('#appMenu').click();await page.locator('#menu [data-command="ai-context"]').click();
 const context2=JSON.parse(await page.locator('#dialogFields .ai-source').inputValue());
 await page.locator('#editorDialog [data-action="close-dialog"]').first().click();
 const packet2={format:'checklist-studio-changes',schemaVersion:1,documentId:'example-overview',baseSha256:context2.baseSha256,operations:[{op:'set-done',id:'purpose',done:true}]};
 await page.locator('#refreshButton').click();
 await page.locator('#refreshInput').setInputFiles({name:'completion.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packet2))});
 await page.waitForFunction(()=>document.getElementById('dialogTitle').textContent==='Review before applying');
 await page.locator('[name="proposedBy"]').fill('Second assistant');await page.locator('[name="confirmCompletion"]').check();await page.locator('#dialogApply').click();
 assert.equal(await page.locator('#center [data-step-row="purpose"] .change-tag').innerText(),'COMPLETED');
 assert.equal(await page.locator('#center [data-step-row="purpose"] .check-highlight').count(),1);
 assert.equal(await page.locator('#trackedUnread').isVisible(),true);
 await page.locator('#trackedLabel').click();assert.equal(await page.locator('#trackedUnread').isVisible(),false);
 // Moving to a new file path is a fresh browser workspace. A first-run import
 // must carry the complete backup, including its history and order.
 const backup=await page.evaluate(()=>Clearings.snapshot());
 const migrated=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await migrated.evaluate(mock);await migrated.setContent(html);
 await migrated.waitForFunction(()=>window.Clearings?.storage().ready);
 await migrated.locator('#importWelcome').click();
 await migrated.locator('#importInput').setInputFiles({name:'workspace.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 await migrated.waitForFunction(()=>document.getElementById('dialogTitle').textContent==='Add to your workspace');
 await migrated.locator('[data-action="import-separate"]').click();
 assert.deepEqual(await migrated.evaluate(()=>Clearings.snapshot()),backup);
 await migrated.close();
 const older=JSON.parse(JSON.stringify(backup));
 older.index.schemaVersion=3;delete older.index.activity;
  delete older.index.preferences.openTopChecklist;delete older.index.preferences.displayName;delete older.index.preferences.showFooterProgress;delete older.index.preferences.showFooterTrack;delete older.index.preferences.clearOnRefreshPress;
 const olderPage=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await olderPage.evaluate(mock);await olderPage.setContent(html);
 await olderPage.waitForFunction(()=>window.Clearings?.storage().ready);
 await olderPage.locator('#importWelcome').click();
 await olderPage.locator('#importInput').setInputFiles({name:'older-workspace.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(older))});
 await olderPage.waitForFunction(()=>document.getElementById('dialogTitle').textContent==='Add to your workspace');
 await olderPage.locator('[data-action="import-separate"]').click();
 assert.deepEqual(await olderPage.evaluate(()=>Clearings.snapshot()),older);
 await olderPage.close();
 const beforeCancelledRefresh=await page.evaluate(()=>Clearings.snapshot().index.activity.map(a=>a.highlight));
 await page.locator('#refreshButton').click();await page.locator('#refreshInput').setInputFiles([]);
 assert.deepEqual(await page.evaluate(()=>Clearings.snapshot().index.activity.map(a=>a.highlight)),beforeCancelledRefresh);
 // On a fresh open, the first incomplete parent opens; deeper levels stay folded.
 const completedStart=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await completedStart.evaluate(mock);await completedStart.setContent(html);
 await completedStart.waitForFunction(()=>window.Clearings?.storage().ready);
 await completedStart.locator('#welcomeName').fill('Test editor');
 await completedStart.locator('#tryExample').click();
 await completedStart.locator('[data-root-group="shape"] > .group-header > .check').check();
 await completedStart.waitForFunction(()=>Clearings.storage().savedAt&&!Clearings.storage().dirty);
 const completedRecord=await completedStart.evaluate(()=>window.__records.get('workspace:local'));
 await completedStart.close();
 const nextStart=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await nextStart.evaluate(mock);await nextStart.evaluate(record=>window.__records.set('workspace:local',record),completedRecord);await nextStart.setContent(html);
 await nextStart.waitForFunction(()=>window.Clearings?.storage().ready);
 assert.equal(await nextStart.locator('[data-root-group="shape"] > ol.rows').count(),0);
 assert.equal(await nextStart.locator('[data-root-group="make"] > ol.rows').count(),1);
 assert.equal(await nextStart.locator('[data-root-group="share"] > ol.rows').count(),0);
 await nextStart.close();
 // A new item may be sent to another checklist; deleting a subtree keeps shared sub-tasks.
 const itemPage=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 await itemPage.evaluate(mock);await itemPage.setContent(html);
 await itemPage.waitForFunction(()=>window.Clearings?.storage().ready);
 await itemPage.locator('#welcomeName').fill('Test editor');
 await itemPage.locator('#tryExample').click();
 await itemPage.locator('[data-root-group="shape"] .group-name').dblclick();
 await itemPage.locator('#addItemButton').click();
 await itemPage.locator('#dialogFields .optional-details > summary').click();
 assert.equal(await itemPage.locator('[name="parentChecklist"]').inputValue(),'example-overview');
 await itemPage.locator('[name="parentChecklist"]').selectOption('example-workshop');
 assert.equal(await itemPage.locator('[data-current-checklist-details]').isHidden(),true);
 assert.match(await itemPage.locator('#itemDestinationHint').innerText(),/top-level item/);
 await itemPage.locator('#dialogFields [name="title"]').fill('Pack the sample kit');
 await itemPage.locator('#editorDialog [data-action="close-dialog"]').first().click();
 await itemPage.locator('#draftNotice [data-action="resume-draft"]').click();
 assert.equal(await itemPage.locator('[name="parentChecklist"]').inputValue(),'example-workshop');
 assert.equal(await itemPage.locator('[data-current-checklist-details]').isHidden(),true);
 await itemPage.locator('#dialogApply').click();
 assert.equal(await itemPage.locator('#pageHeader h1').innerText(),'Weekend Workshop');
 let itemState=await itemPage.evaluate(()=>Clearings.snapshot());
 assert.equal(itemState.documents.find(d=>d.documentId==='example-overview').model.items.some(i=>i.text==='Pack the sample kit'),false);
 const workshop=itemState.documents.find(d=>d.documentId==='example-workshop');
 assert.equal(workshop.model.items.some(i=>i.text==='Pack the sample kit'),true);
 assert.ok(workshop.model.roots.includes(workshop.model.items.find(i=>i.text==='Pack the sample kit').id));
 await itemPage.locator('#libraryList [data-library-id="example-overview"] .library-open').click();
 await itemPage.locator('[data-root-group="shape"] .group-name').dblclick();
 await itemPage.locator('#addItemButton').click();
 await itemPage.locator('#dialogFields [name="title"]').fill('Write a local note');
 await itemPage.locator('#dialogApply').click();
 itemState=await itemPage.evaluate(()=>Clearings.snapshot());
 const localNote=itemState.documents.find(d=>d.documentId==='example-overview').model.items.find(i=>i.text==='Write a local note');
 assert.ok(itemState.documents.find(d=>d.documentId==='example-overview').model.items.find(i=>i.id==='shape').requires.includes(localNote.id));
 await itemPage.locator('#breadcrumbs [data-action="open-checklist"]').click();
 await itemPage.locator('[data-root-group="make"] > .group-header [data-menu="step"]').click();
 await itemPage.locator('#menu [data-command="edit-step"]').click();
 await itemPage.locator('#dialogFields .optional-details details > summary').click();
 await itemPage.locator('#dialogFields [name="requires"][value="purpose"]').check();
 await itemPage.locator('#dialogApply').click();
 await itemPage.locator('[data-root-group="shape"] > .group-header [data-menu="step"]').click();
 assert.equal(await itemPage.locator('#menu [data-command="new-subitem"]').innerText(),'Add new item');
 itemPage.once('dialog',dialog=>{assert.match(dialog.message(),/shared sub-task/);dialog.dismiss()});
 await itemPage.locator('#menu [data-command="delete-step-all"]').click();
 assert.ok((await itemPage.evaluate(()=>Clearings.snapshot())).documents.find(d=>d.documentId==='example-overview').model.items.some(i=>i.id==='shape'));
 await itemPage.locator('[data-root-group="shape"] > .group-header [data-menu="step"]').click();
 itemPage.once('dialog',dialog=>dialog.accept());
 await itemPage.locator('#menu [data-command="delete-step-all"]').click();
 itemState=await itemPage.evaluate(()=>Clearings.snapshot());
 const afterDelete=itemState.documents.find(d=>d.documentId==='example-overview');
 assert.equal(afterDelete.model.items.some(i=>i.id==='shape'||i.id==='first-look'),false);
 assert.equal(afterDelete.model.items.some(i=>i.id==='purpose'),true);
 assert.equal(afterDelete.model.items.find(i=>i.id==='make').requires.includes('purpose'),true);
 validateWorkspace(itemState);
 await itemPage.locator('#toast [data-action="undo"]').click();
 itemState=await itemPage.evaluate(()=>Clearings.snapshot());
 assert.equal(itemState.documents.find(d=>d.documentId==='example-overview').model.items.some(i=>i.id==='shape'),true);
 await itemPage.locator('[data-root-group="shape"] > .group-header [data-menu="step"]').click();
 itemPage.once('dialog',dialog=>dialog.accept());
 await itemPage.locator('#menu [data-command="delete-step"]').click();
 itemState=await itemPage.evaluate(()=>Clearings.snapshot());
 const promoted=itemState.documents.find(d=>d.documentId==='example-overview');
 assert.equal(promoted.model.items.some(i=>i.id==='shape'),false);
 assert.ok(promoted.model.roots.includes('first-look'));
 validateWorkspace(itemState);
 await itemPage.close();
 const templatePage=await browser.newPage({viewport:{width:1440,height:980},bypassCSP:true});
 templatePage.on('pageerror',e=>errors.push(e.message));
 await templatePage.exposeFunction('__digest',bytes=>[...createHash('sha256').update(Buffer.from(bytes)).digest()]);
 await templatePage.evaluate(mock);
 await templatePage.evaluate(()=>Object.defineProperty(crypto,'subtle',{configurable:true,value:{digest:async(_algorithm,bytes)=>Uint8Array.from(await __digest([...new Uint8Array(bytes)])).buffer}}));
 await templatePage.setContent(html);
 await templatePage.waitForFunction(()=>window.Clearings?.storage().ready);
 await templatePage.locator('#welcomeName').fill('Template tester');
 await templatePage.locator('#tryExample').click();
 await templatePage.locator('#appMenu').click();
 await templatePage.locator('[data-command="templates"]').click();
 assert.equal(await templatePage.locator('#dialogTitle').innerText(),'Templates');
 await templatePage.locator('[data-action="choose-template"][data-template="clearings-github-patch-v1"]').click();
 assert.equal(await templatePage.locator('[data-action="template-new"]').count(),1);
 assert.equal(await templatePage.locator('[data-action="template-add"]').count(),1);
 await templatePage.locator('[data-action="template-new"]').click();
 let templateState=await templatePage.evaluate(()=>Clearings.snapshot());
 const newPatch=templateState.documents.find(d=>d.title==='Clearings · GitHub patch update');
 assert.ok(newPatch&&newPatch.documentId!=='clearings-github-patch-v1');
 assert.deepEqual(newPatch.state,{});
 assert.equal(templateState.documents.length,3);
 const originalOverview=structuredClone(templateState.documents.find(d=>d.documentId==='example-overview'));
 await templatePage.locator('#appMenu').click();
 await templatePage.locator('[data-command="local-settings"]').click();
 await templatePage.locator('[data-action="templates"]').click();
 await templatePage.locator('[data-action="choose-template"][data-template="clearings-github-release-v1"]').click();
 await templatePage.locator('[data-action="template-add"]').click();
 await templatePage.locator('[name="targetChecklist"]').selectOption('example-overview');
 await templatePage.locator('[name="parentItem"]').selectOption('shape');
 await templatePage.locator('#dialogApply').click();
 templateState=await templatePage.evaluate(()=>Clearings.snapshot());
 const expanded=templateState.documents.find(d=>d.documentId==='example-overview');
 const addedGroup=expanded.model.items.find(i=>i.text==='Clearings · GitHub release');
 assert.ok(addedGroup&&expanded.model.items.find(i=>i.id==='shape').requires.includes(addedGroup.id));
 assert.ok(addedGroup.requires.length>0);
 assert.deepEqual(expanded.state,originalOverview.state);
 assert.equal(templateState.documents.length,3,'Adding under an item must not create a fourth checklist');
 validateWorkspace(templateState);
 await templatePage.close();
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('Clearings 0.4 isolated browser checks passed (native Firefox file persistence is separate).');
})().catch(error=>{console.error(error);process.exitCode=1});
